version: '3.8'

services:
  ecodrive-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecodrive-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5000
      - WORKERS=4
      - LOG_LEVEL=info
    volumes:
      # Mount models directory if you want to persist trained models
      - ./backend/models:/app/backend/models:ro
      # Mount FastF1 cache for faster data loading
      - ./backend/fastf1_cache:/app/backend/fastf1_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

